"""add scan_policies table

Revision ID: 22ecc813615a
Revises: 43dda1dd67bc
Create Date: 2026-08-22 05:58:06.177621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '22ecc813615a'
down_revision: Union[str, None] = '43dda1dd67bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM_CRON', name='scanfrequency'), nullable=False),
    sa.Column('cron_expression', sa.String(), nullable=True),
    sa.Column('scope', sa.Enum('PASSIVE', 'ACTIVE', 'FULL', name='scanscope'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_policies_asset_id'), 'scan_policies', ['asset_id'], unique=False)
    op.create_index(op.f('ix_scan_policies_organization_id'), 'scan_policies', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_policies_organization_id'), table_name='scan_policies')
    op.drop_index(op.f('ix_scan_policies_asset_id'), table_name='scan_policies')
    op.drop_table('scan_policies')
    # ### end Alembic commands ###