"""add subdomain_ips table, asset.criticality, port.banner

Revision ID: c94ef53a231e
Revises: 3c92fd862a87
Create Date: 2026-08-21 17:34:10.727556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c94ef53a231e'
down_revision: Union[str, None] = '3c92fd862a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdomain_ips',
    sa.Column('subdomain_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subdomain_id', 'ip_address')
    )
    op.add_column('assets', sa.Column('criticality', sa.String(), nullable=False))
    op.add_column('ports', sa.Column('banner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ports', 'banner')
    op.drop_column('assets', 'criticality')
    op.drop_table('subdomain_ips')
    # ### end Alembic commands ###